# This workflow will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AppBuildProduction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements/production.txt ]; then pip install -r requirements/production.txt; fi
    - name: Run PyTest
      run: |
        pytest
